### ISSUE TITLE
`dist` directory not included in v2.1.0

### ISSUE THREAD

**Issue by kwaa** [frencojobs/fenceparser#10]
https://www.jsdelivr.com/package/npm/fenceparser

###### v2.1.0
![2.1.0](https://user-images.githubusercontent.com/50108258/182767580-554facad-2934-4a8f-803e-3b3674c1fc28.png)

###### v2.0.0
![2.0.0](https://user-images.githubusercontent.com/50108258/182767682-c24c4756-d72f-4584-95f1-cbc7f066a547.png)

**Comment by frencojobs** [comment]
Oh my god, I messed up big time here. I forgot to add build steps to GitHub Actions to all of my previously updated packages 🤦‍♂️. Thanks for pointing it out, releasing a fix asap.

**Comment by frencojobs** [comment]
Hi @kwaa it's fixed in v2.1.1 now. Again, thanks for reporting this.
